#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Reference: https://github.com/jarrodwatts/code-like-google
echo '🏗️👷 Styling and linting  your project before committing'

# Check Prettier standards
npx lint-staged  ||
(
    echo '❌❌❌❌❌ Failed ESLint and Prettier. ❌❌❌❌❌
            Prettier and ESLint Check Failed. Make the required changes listed above, add changes and try commit again.';
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'